apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-registry
  labels:
    app: device-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: device-registry
  template:
    metadata:
      labels:
        app: device-registry
    spec:
      containers:
      - name: device-registry
        image: andyy5/device-registry
---
apiVersion: v1
kind: Service
metadata:
  name: device-registry
  labels:
    app: device-registry
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: device-registry